environments:
  dev:
  stg:
  prd:

repositories:
- name: "external-secrets"
  url: "https://external-secrets.github.io/kubernetes-external-secrets/"

releases:
- name: "kubernetes-external-secrets"
  namespace: "external-secrets"
  labels:
    chart: "kubernetes-external-secrets"
    repo: "external-secrets"
    component: "kubernetes-external-secrets"
    namespace: "external-secrets"
    vendor: "kubernetes"
  chart: "external-secrets/kubernetes-external-secrets"
  version: "8.4.0"
  wait: false
  timeout: 360
  values:
    - ./values.default.yaml
    - ./values.{{ .Environment.Name }}.yaml
