apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-api
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: demo
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:${repo_name}
    targetRevision: main
    path:
