environments:
  dev:
  stg:
  prd:

repositories:
- name: "bitnami"
  url: "https://charts.bitnami.com/bitnami"

releases:
- name: "external-dns"
  namespace: "external-dns"
  labels:
    chart: "external-dns"
    repo: "stable"
    component: "dns"
    namespace: "kube-system"
    vendor: "kubernetes"
  chart: "bitnami/external-dns"
  version: "5.4.11"
  wait: true
  waitForJobs: true
  disableValidationOnInstall: true
  timeout: 180
  atomic: true
  values:
    - ./values.default.yaml
    - ./values.{{ .Environment.Name }}.yaml
