apiVersion: v1
kind: Service
metadata:
  name: backend-api
  labels:
    app: backend-api
    service: backend-api
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8011
      targetPort: 8011
  type: ClusterIP
  clusterIP: None
  selector:
    app: backend-api
    tier: api
