apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/backend-api-eks-role
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
