apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: backend-api-envs-secrets
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  backendType: secretsManager
  region: us-west-2
  data:
    - name: DATABASE_PASSWORD
      key: ${credential_key}
      property: password
